config/routes.rb
Rails.application.routes.draw do
  resources :users, param: :username do
    resources :notes
  end
  get '/users/:username/admin', to: 'users#grant_admin', as: :user_grant_admin
  get '/users/:username/moderator', to: 'users#grant_moderator', as: :user_grant_moderator
  get '/users/:username/block', to: 'users#block', as: :user_block
  post '/users/is_local_username', to: 'users#is_local_username'
  get '/users/search/users', to: 'users#search_users'

  resources :groups, param: :group_name

  resources :delayable_contests, controller: 'contests', type: 'DelayableContest', except: :show

  get '/contests', to: 'contests#index', as: :contests
  post '/contests', to: 'contests#create'
  get '/contests/new', to: 'contests#new', as: :new_contest
  get '/c/:slug/:id', to: 'contests#show', constraints: {id: /\d+/}, as: :contest
  get '/c/:slug/:id/edit', to: 'contests#edit', constraints: {id: /\d+/}, as: :edit_contest
  match '/c/:slug/:id', to: 'contests#update', constraints: {id: /\d+/}, via: [:patch, :put]
  delete '/c/:slug/:id', to: 'contests#destroy', constraints: {id: /\d+/}
  get 'c/:slug/:id/notifications/new', to: 'contests#new_notification', constraints: {id: /\d+/}, as: :new_contest_notification
  post 'c/:slug/:id/notifications', to: 'contests#create_notification', constraints: {id: /\d+/}, as: :contest_notifications
  get '/c/:slug/:id/ranking', to: 'contests#ranking', constraints: {id: /\d+/}, as: :contest_ranking
  get '/c/:slug/:contest_id/solutions', to: 'contests#solutions', constraints: {contest_id: /\d+/}, as: :contest_solutions
  post '/c/:slug/:contest_id/solutions', to: 'contests#create_solution', constraints: {contest_id: /\d+/}
  get '/c/:slug/:contest_id/posts', to: 'posts#index_with_contest', constraints: {contest_id: /\d+/}, as: :contest_posts
  post '/c/:slug/:contest_id/posts', to: 'posts#create_with_contest', constraints: {contest_id: /\d+/}
  get '/c/:slug/:contest_id/posts/new', to: 'posts#new_with_contest', constraints: {contest_id: /\d+/}, as: :new_contest_post
  get '/c/:slug/:contest_id/:post_id', to: 'posts#show_with_contest', constraints: {contest_id: /\d+/, post_id: /\d+/}, as: :contest_post

  resources :posts do
    put '/pinned', to: 'posts#toggle_pinned', as: :pinned
    put '/visible', to: 'posts#toggle_visible', as: :visible
    resources :comments
  end
  resources :solutions do
    get '/report', to: 'solutions#report'
  end
  get '/problems', to: 'problems#index', as: :problems
  post '/problems', to: 'problems#create'
  get '/problems/new', to: 'problems#new', as: :new_problem
  get '/p/:slug/:id', to: 'problems#show', constraints: {id: /\d+/}, as: :problem
  get '/p/:slug/:id/edit', to: 'problems#edit', constraints: {id: /\d+/}, as: :edit_problem
  match '/p/:slug/:id', to: 'problems#update', constraints: {id: /\d+/}, via: [:patch, :put]
  delete '/p/:slug/:id', to: 'problems#destroy', constraints: {id: /\d+/}
  get '/p/:slug/:problem_id/posts', to: 'posts#index_with_problem', constraints: {id: /\d+/}, as: :problem_posts
  post '/p/:slug/:problem_id/posts', to: 'posts#create_with_problem', constraints: {id: /\d+/}
  get '/p/:slug/:problem_id/posts/new', to: 'posts#new_with_problem', constraints: {id: /\d+/}, as: :new_problem_post
  get '/p/:slug/:problem_id/posts/:post_id', to: 'posts#show_with_problem', constraints: {id: /\d+/}, as: :problem_post
  delete '/p/:slug/:id', to: 'problems#destroy', constraints: {id: /\d+/}
  post '/problems/import', to: 'problems#import', as: :problems_import
  get '/problems/:id/excerpt', to: 'problems#excerpt'
  get '/p/:slug/:problem_id/solutions', to: 'problems#solutions', constraints: { problem_id: /\d+/ }, as: :problem_solutions
  post '/p/:slug/:problem_id/solutions', to: 'problems#create_solution', constraints: { problem_id: /\d+/ }

  namespace :admin do
    get '/dashboard', to: 'admin#dashboard'
    scope :settings do
      get '/:category', to: 'admin#show_settings', as: :settings
      put '/:category', to: 'admin#update_settings'
    end
    get '/groups', to: 'admin#groups', as: :groups
    post '/groups', to: 'admin#create_group'
    get '/groups/:group_name', to: 'admin#group', as: :group
    put '/groups/:group_name', to: 'admin#update_group'
    get '/uploads', to: 'admin#uploads_index', as: :uploads

    root to: 'admin#dashboard'
  end

  resources :uploads

  post '/preview/text', to: 'preview#preview_text', as: :preview_text
  post '/preview/code', to: 'preview#preview_code', as: :preview_code

  get '/settings/profile', to: 'user_settings#profile', as: :settings_profile
  post '/settings/profile', to: 'user_settings#update_profile'
  get '/settings/account', to: 'user_settings#account', as: :settings_account
  post '/settings/account', to: 'user_settings#update_account'
  post '/settings/email', to: 'user_settings#update_email', as: :settings_email
  get '/settings/notifications', to: 'user_settings#notification', as: :settings_notification
  post '/settings/notifications', to: 'user_settings#update_notification'

  get '/signup', to: 'users#new', as: :registration
  get '/login', to: 'sessions#new', as: :login
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy', as: :logout
  get '/about', to: 'statics#about', as: :about
  get '/help', to: 'statics#help', as: :help

  get '/query', to: 'search#query'
  get '/notifications', to: 'notifications#recent'
  post '/notifications/read', to: 'notifications#read'

  get '/rabbitmq', to: 'proxies#rabbitmq'

  root to: 'statics#home'
end

app/models/user.rb
require 'pbkdf2'

class User < ActiveRecord::Base
  include Searchable

  attr_accessor :password_confirmation

  has_one :user_stat, dependent: :destroy
  has_one :user_search_data, dependent: :destroy
  has_many :solutions, dependent: :destroy
  has_many :posts
  has_many :comments
  has_many :contests
  has_many :problems
  has_many :user_problem_stats, dependent: :destroy
  has_many :group_users, dependent: :destroy
  has_many :groups, through: :group_users
  has_many :notifications

  attachment :avatar, type: :image

  scope :real, -> { where('id > 0') }

  before_validation :downcase_email

  validates_presence_of :username
  validate :username_validator
  validates :email, presence: true, uniqueness: true
  validates :email, email: true, if: :email_changed?
  validate :password_validator, on: [:create]

  before_create :build_user_stat
  before_create :set_default_platform

  before_save :update_username_lower
  before_save :ensure_password_is_hashed

  after_initialize :set_default_active

  def self.username_length
    2..20
  end

  def self.max_password_length
    200
  end

  def self.new_token
    SecureRandom.urlsafe_base64
  end

  def self.find_by_email(email)
    find_by(email: email.downcase)
  end

  def self.find_by_username(username)
    find_by(username_lower: username.downcase)
  end

  def self.find_by_username_or_email(username_or_email)
    if username_or_email.include?('@')
      find_by_email username_or_email
    else
      find_by_username username_or_email
    end
  end

  def self.username_available?(username)
    lower = username.downcase
    User.where(username_lower: lower).blank?
  end

  def update_index
    return unless username_changed? || name_changed?

    User.update_search_index 'user', self.id, "#{username} #{name}"
  end

  def update_username_lower
    self.username_lower = username.downcase
  end

  def downcase_email
    self.email.downcase! if self.email
  end

  def username_format_validator
    UsernameValidator.perform_validation(self, 'username')
  end

  def username_validator
    username_format_validator || begin
      existing = User.find_by(username_lower: username.downcase)
      if username_changed? && existing && existing.id != self.id
        errors.add(:username, I18n.t('user.username.unique'))
      end
    end
  end

  def password=(password)
    @raw_password = password unless password.blank?
  end

  def password
    @raw_password
  end

  def password_validator
    errors.add(:password_confirmation, :invalid) if password_confirmation != @raw_password
    PasswordValidator.new(attributes: :password).validate_each(self, :password, @raw_password)
  end

  def ensure_password_is_hashed
    if @raw_password
      self.salt = SecureRandom.hex(16)
      self.password_hash = hash_password(@raw_password, salt)
    end
  end

  def hash_password(password, salt)
    raise 'password is too long' if password.length > User.max_password_length
    Pbkdf2.hash_password(password, salt, Rails.configuration.pbkdf2_iterations, Rails.configuration.pbkdf2_algorithm)
  end

  def set_default_active
    self.active = true
  end

  def authenticate!(password)
    return false unless password_hash && salt
    self.password_hash == hash_password(password, salt)
  end

  def change_username(new_username)
    self.username = new_username
    save
  end

  def update_last_seen!(now=Time.zone.now)
    update_column(:last_seen_at, now)
  end

  def username_format_validator
    UsernameValidator.perform_validation(self, 'username')
  end

  def to_param
    username_lower
  end

  def staff?
    moderator? || admin?
  end

  def set_default_platform
    self.default_platform = 'C++'
  end

end

# == Schema Information
#
# Table name: users
#
#  id                      :integer          not null, primary key
#  username                :string(60)       not null
#  name                    :string(320)
#  email                   :string(300)      not null
#  password_hash           :string(64)
#  salt                    :string(32)
#  active                  :boolean          default(FALSE), not null
#  last_seen_at            :datetime
#  admin                   :boolean          default(FALSE), not null
#  ip_address              :inet
#  registration_ip_address :inet
#  auth_token              :string(60)
#  username_lower          :string(60)       not null
#  suspended               :boolean          default(FALSE), not null
#  suspended_at            :datetime
#  suspended_till          :datetime
#  last_emailed_at         :datetime
#  moderator               :boolean          default(FALSE)
#  blocked                 :boolean          default(FALSE)
#  email_notification      :boolean          default(TRUE)
#  email_digest            :boolean          default(FALSE)
#  email_contest_result    :boolean          default(TRUE)
#  email_solution_result   :boolean          default(FALSE)
#  avatar_id               :string
#  avatar_filename         :string
#  show_email              :boolean          default(TRUE), not null
#  website                 :string(255)
#  crew                    :string
#  student_id              :string
#
# Indexes
#
#  index_users_on_avatar_filename  (avatar_filename) UNIQUE
#  index_users_on_email            (email) UNIQUE
#  index_users_on_last_seen_at     (last_seen_at)
#  index_users_on_username         (username) UNIQUE
#  index_users_on_username_lower   (username_lower) UNIQUE
#

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def search_users
    authorize current_user, :search?

    term = params[:term].to_s.strip
    users = User.where(active: true).order(User.sql_fragment("CASE WHEN username = ? THEN 0 ELSE 1 END ASC", term.downcase))

    if term.present?
      query = Search.ts_query(term)
      term_like = "#{term.downcase}%"
      users = users.includes(:user_search_datas)
                   .references(:user_search_datas)
                   .where("username LIKE :term_like OR user_search_datas.search_data @@ #{query}",
                          term: term, term_like: term_like)
                   .order(User.sql_fragment("CASE WHEN username LIKE ? THEN 0 ELSE 1 END ASC", term_like))
    end

    render_serialized(users, BasicUserSerializer)
  end

  def new
    @user = User.new
    authorize @user
  end

  def create
    @user = User.new(user_params)
    authorize @user

    if @user.save
      flash[:success] = "Successfully created your account. You can log in now."
      redirect_to login_path
    else
      flash[:danger] = "There were problems creating your account."
      render 'new'
    end
  end

  def show
    @user = User.includes(:groups).find_by(username_lower: params[:username].downcase)
    authorize @user
    @groups = @user.groups
    @problems = policy_scope(Problem)
                    .includes(:user_problem_stats)
                    .where(user_problem_stats: { user_id: @user.id })
                    .where.not(user_problem_stats: { state: 'null' })
                    .order(:id)
                    .page(params[:page])
                    .per(30)
  end

  def edit
    @user = User.find_by(username_lower: params[:username])
    authorize @user
  end

  def is_local_username
    params.require(:username)
    u = params[:username].downcase
    r = User.exec_sql('SELECT 1 FROM users WHERE username_lower = ?', u).values
    render json: {valid: r.length == 1}
  end

  def grant_admin
    user = User.find_by(username: params[:username])
    authorize current_user, :admin?
    if user
      user.update_attribute(:admin, !user.admin) unless current_user == user

      redirect_to user_path(user)
    else
      render nothing: 200
    end
  end

  def grant_moderator
    user = User.find_by(username: params[:username])
    authorize current_user, :admin?
    if user
      user.update_attribute(:moderator, !user.moderator) unless current_user == user

      redirect_to user_path(user)
    else
      render nothing: 200
    end
  end

  def block
    user = User.find_by(username: params[:username])
    authorize current_user, :admin?
    if user && current_user != user
      user.block = !user.block
      user.active = !user.block
      user.save!

      redirect_to user_path(user)
    else
      render nothing: 200
    end
  end

  private

  def user_params
    params.require(:user).permit(*policy(@user || User).permitted_attributes)
  end
end

app/views/users/settings/_navlist.html.haml
.col-md-3
  .list-group
    %h5.list-group-item Personal settings
    = link_to 'Profile', settings_profile_path, class: "list-group-item #{active_if('profile')}"
    = link_to 'Account settings', settings_account_path, class: "list-group-item #{active_if('account')}"
    -#= link_to 'Notification center', settings_notification_path, class: "list-group-item #{active_if('notification')}"

app/views/users/settings/account.html.haml
- content_for :title, 'Account'

.row
  = render 'users/settings/navlist'
  .col-md-9
    .panel.setting-panel.panel-default
      .panel-heading
        %h3.panel-title Change password
      .panel-body
        = form_for current_user, html: {role: 'form'}, url: settings_account_path, method: :post do |f|
          .form-group
            = f.label :old_password
            = f.password_field :old_password, class: 'form-control'
          .form-group
            = f.label :new_password
            = f.password_field :new_password, class: 'form-control'
          .form-group
            = f.label :confirmation_password
            = f.password_field :confirmation_password, class: 'form-control'
          = f.submit 'Update password', class: 'btn btn-default'
    .panel.setting-panel.panel-default
      .panel-heading
        %h3.panel-title Change email
      .panel-body
        = form_for current_user, html: {role: 'form'}, url: settings_email_path, method: :post do |f|
          %p Changing your username can have unintended side effects.
          .form-group
            = f.label :email
            = f.text_field :email, class: 'form-control'
          = f.submit 'Change email', class: 'btn btn-default'
    -#.panel.setting-panel.panel-default
    -#  .panel-heading
    -#    %h3.panel-title Delete account
    -#  .panel-body
    -#    = form_for current_user, html: {role: 'form'}, url: user_path(current_user), method: :delete do |f|
    -#      = f.submit 'DELETE your account', class: 'btn btn-danger'

app/views/users/settings/notification.html.haml
.row
  = render 'users/settings/navlist'
  .col-md-9
    - flash.each do |name, msg|
      %div{:class => "alert alert-#{name} alert-dismissible", :role => "alert"}
        %button.close{"data-dismiss" => "alert", :type => "button"}
          %span{"aria-hidden" => "true"} &times;
          %span.sr-only Close
        = msg
    .panel.setting-panel.panel-default
      .panel-heading
        %h3.panel-title How you receive notifications
      .panel-body

app/views/users/settings/profile.html.haml
- content_for :title, 'Profile'

.row
  = render 'users/settings/navlist'
  .col-md-9
    .panel.setting-panel.panel-default
      .panel-heading
        %h3.panel-title Public profile
      .panel-body
        = form_for current_user, html: {role: 'form'}, url: settings_profile_path, method: :post do |f|
          .form-group
            = f.label :avatar
            = f.file_field :avatar
          .form-group
            = f.label :username
            = f.text_field :username, class: 'form-control'
          .form-group
            = f.label :name
            = f.text_field :name, class: 'form-control'
          .form-group
            = f.label :crew, 'Class'
            = f.text_field :crew, class: 'form-control'
          .form-group
            = f.label :student_id
            = f.text_field :student_id, class: 'form-control'
          .form-group
            = f.label :website
            = f.text_field :website, class: 'form-control'
          = f.submit 'Update profile', class: 'btn btn-success'