config/routes.rb
Rails.application.routes.draw do
  resources :users, param: :username do
    resources :notes
  end
  get '/users/:username/admin', to: 'users#grant_admin', as: :user_grant_admin
  get '/users/:username/moderator', to: 'users#grant_moderator', as: :user_grant_moderator
  get '/users/:username/block', to: 'users#block', as: :user_block
  post '/users/is_local_username', to: 'users#is_local_username'
  get '/users/search/users', to: 'users#search_users'

  resources :groups, param: :group_name

  resources :delayable_contests, controller: 'contests', type: 'DelayableContest', except: :show

  get '/contests', to: 'contests#index', as: :contests
  post '/contests', to: 'contests#create'
  get '/contests/new', to: 'contests#new', as: :new_contest
  get '/c/:slug/:id', to: 'contests#show', constraints: {id: /\d+/}, as: :contest
  get '/c/:slug/:id/edit', to: 'contests#edit', constraints: {id: /\d+/}, as: :edit_contest
  match '/c/:slug/:id', to: 'contests#update', constraints: {id: /\d+/}, via: [:patch, :put]
  delete '/c/:slug/:id', to: 'contests#destroy', constraints: {id: /\d+/}
  get 'c/:slug/:id/notifications/new', to: 'contests#new_notification', constraints: {id: /\d+/}, as: :new_contest_notification
  post 'c/:slug/:id/notifications', to: 'contests#create_notification', constraints: {id: /\d+/}, as: :contest_notifications
  get '/c/:slug/:id/ranking', to: 'contests#ranking', constraints: {id: /\d+/}, as: :contest_ranking
  get '/c/:slug/:contest_id/solutions', to: 'contests#solutions', constraints: {contest_id: /\d+/}, as: :contest_solutions
  post '/c/:slug/:contest_id/solutions', to: 'contests#create_solution', constraints: {contest_id: /\d+/}
  get '/c/:slug/:contest_id/posts', to: 'posts#index_with_contest', constraints: {contest_id: /\d+/}, as: :contest_posts
  post '/c/:slug/:contest_id/posts', to: 'posts#create_with_contest', constraints: {contest_id: /\d+/}
  get '/c/:slug/:contest_id/posts/new', to: 'posts#new_with_contest', constraints: {contest_id: /\d+/}, as: :new_contest_post
  get '/c/:slug/:contest_id/:post_id', to: 'posts#show_with_contest', constraints: {contest_id: /\d+/, post_id: /\d+/}, as: :contest_post

  resources :posts do
    put '/pinned', to: 'posts#toggle_pinned', as: :pinned
    put '/visible', to: 'posts#toggle_visible', as: :visible
    resources :comments
  end
  resources :solutions do
    get '/report', to: 'solutions#report'
  end
  get '/problems', to: 'problems#index', as: :problems
  post '/problems', to: 'problems#create'
  get '/problems/new', to: 'problems#new', as: :new_problem
  get '/p/:slug/:id', to: 'problems#show', constraints: {id: /\d+/}, as: :problem
  get '/p/:slug/:id/edit', to: 'problems#edit', constraints: {id: /\d+/}, as: :edit_problem
  match '/p/:slug/:id', to: 'problems#update', constraints: {id: /\d+/}, via: [:patch, :put]
  delete '/p/:slug/:id', to: 'problems#destroy', constraints: {id: /\d+/}
  get '/p/:slug/:problem_id/posts', to: 'posts#index_with_problem', constraints: {id: /\d+/}, as: :problem_posts
  post '/p/:slug/:problem_id/posts', to: 'posts#create_with_problem', constraints: {id: /\d+/}
  get '/p/:slug/:problem_id/posts/new', to: 'posts#new_with_problem', constraints: {id: /\d+/}, as: :new_problem_post
  get '/p/:slug/:problem_id/posts/:post_id', to: 'posts#show_with_problem', constraints: {id: /\d+/}, as: :problem_post
  delete '/p/:slug/:id', to: 'problems#destroy', constraints: {id: /\d+/}
  post '/problems/import', to: 'problems#import', as: :problems_import
  get '/problems/:id/excerpt', to: 'problems#excerpt'
  get '/p/:slug/:problem_id/solutions', to: 'problems#solutions', constraints: { problem_id: /\d+/ }, as: :problem_solutions
  post '/p/:slug/:problem_id/solutions', to: 'problems#create_solution', constraints: { problem_id: /\d+/ }

  namespace :admin do
    get '/dashboard', to: 'admin#dashboard'
    scope :settings do
      get '/:category', to: 'admin#show_settings', as: :settings
      put '/:category', to: 'admin#update_settings'
    end
    get '/groups', to: 'admin#groups', as: :groups
    post '/groups', to: 'admin#create_group'
    get '/groups/:group_name', to: 'admin#group', as: :group
    put '/groups/:group_name', to: 'admin#update_group'
    get '/uploads', to: 'admin#uploads_index', as: :uploads

    root to: 'admin#dashboard'
  end

  resources :uploads

  post '/preview/text', to: 'preview#preview_text', as: :preview_text
  post '/preview/code', to: 'preview#preview_code', as: :preview_code

  get '/settings/profile', to: 'user_settings#profile', as: :settings_profile
  post '/settings/profile', to: 'user_settings#update_profile'
  get '/settings/account', to: 'user_settings#account', as: :settings_account
  post '/settings/account', to: 'user_settings#update_account'
  post '/settings/email', to: 'user_settings#update_email', as: :settings_email
  get '/settings/notifications', to: 'user_settings#notification', as: :settings_notification
  post '/settings/notifications', to: 'user_settings#update_notification'

  get '/signup', to: 'users#new', as: :registration
  get '/login', to: 'sessions#new', as: :login
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy', as: :logout
  get '/about', to: 'statics#about', as: :about
  get '/help', to: 'statics#help', as: :help

  get '/query', to: 'search#query'
  get '/notifications', to: 'notifications#recent'
  post '/notifications/read', to: 'notifications#read'

  get '/rabbitmq', to: 'proxies#rabbitmq'

  root to: 'statics#home'
end

app/models/post.rb
require 'pretty_text'

class Post < ActiveRecord::Base
  has_one :post_search_data, dependent: :destroy
  has_many :comments, -> { order('comment_number ASC') }, dependent: :destroy
  has_many :notifications
  belongs_to :contest
  belongs_to :problem
  belongs_to :user

  scope :published, -> { where(published: true) }
  scope :pinned, -> { where(pinned: true) }

  validates :title, length: { in: 2..60 }, presence: true

  def first_comment
    comments.first
  end
end

# == Schema Information
#
# Table name: posts
#
#  id            :integer          not null, primary key
#  title         :string           not null
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  published     :boolean          default(FALSE), not null
#  pinned        :boolean          default(FALSE)
#  comment_count :integer          default(0), not null
#  contest_id    :integer
#  user_id       :integer
#

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = policy_scope(Post.all).page(params[:page]).per(20)
  end

  def new
    @post = Post.new
    authorize @post
  end

  def create
    authorize :post
    creator = CommentCreator.new(current_user, post_params.merge(title: params[:post][:title]))
    @comment = creator.create
    @post = @comment.post
    unless creator.errors.any? || @comment.errors.any?
      redirect_to post_path(@post)
    else
      flash[:danger] = 'Error creating the post.'
      render 'new'
    end
  end

  def show
    @post = Post.find(params[:id])
    authorize @post
    @comment = Comment.new
  end

  def edit
    @post = Post.find(params[:id])
    authorize @post
  end

  def update
    @post = Post.find(params[:id])
    authorize @post
    @comment = @post.first_comment
    @comment.raw = params[:comment][:raw]

    if @post.save && @comment.save
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    authorize @post

    if @post.destroy
      redirect_to posts_path
    end
  end

  def toggle_pinned
    @post = Post.find(params[:post_id])
    authorize @post, :destroy?

    if @post.update_attribute(:pinned, !@post.pinned)
      render json: success_json
    else
      render json: failed_json, status: 400
    end
  end

  def toggle_visible
    @post = Post.find(params[:post_id])
    authorize @post, :destroy?

    if @post.update_attribute(:visible, !@post.visible)
      render json: success_json
    else
      render json: failed_json, status: 400
    end
  end

  def index_with_contest
    @contest = Contest.find(params[:contest_id])
    authorize @contest, :rejudge_solution?
    @posts = @contest.posts
  end

  def new_with_contest
    @contest = Contest.find(params[:contest_id])
    authorize @contest, :create_solution?
    @post = Post.new
    @posts = @contest.posts.where(user_id: current_user.id)
    render :new
  end

  def create_with_contest
    @contest = Contest.find(params[:contest_id])
    authorize @contest, :create_solution?
    creator = CommentCreator.new(current_user, post_params.merge(title: params[:post][:title], contest_id: @contest.id))
    @comment = creator.create
    @post = @comment.post
    unless creator.errors.any?
      redirect_to contest_post_path(@contest.slug, @contest.id, @post.id)
    else
      flash[:danger] = 'Error creating the post.'
      render :new
    end
  end

  def show_with_contest
    @post = Post.find(params[:post_id])
    @comment = Comment.new
    authorize @post

    render :show
  end

  def index_with_problem
    @problem = Problem.find(params[:problem_id])
    authorize @problem, :show?
    @posts = @problem.posts
  end

  def new_with_problem
    @problem = Problem.find(params[:problem_id])
    authorize @problem, :show?
    @post = Post.new
    render :new
  end

  def create_with_problem
    @problem = Problem.find(params[:problem_id])
    authorize @problem, :show?
    creator = CommentCreator.new(current_user, post_params.merge(title: params[:post][:title], problem_id: @problem.id))
    @comment = creator.create
    @post = @comment.post
    unless creator.errors.any?
      redirect_to problem_post_path(@problem.slug, @problem.id, @post.id)
    else
      flash[:danger] = 'Error creating the post.'
      render :new
    end
  end

  def show_with_problem
    @problem = Problem.find(params[:problem_id])
    @post = Post.find(params[:post_id])
    @comment = Comment.new
    authorize @problem, :show?

    render :show
  end

  private

  def post_params
    params.require(:comment).permit(*policy(@post || Post).permitted_attributes)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.haml
.form-group
  = f.label :title, 'Post title'
  = text_field_tag 'post[title]', @post && @post.title, class: 'form-control', id: 'post-title', placeholder: 'Title'
.form-group
  = render partial: 'components/source_editor',  |
    locals: {                                    |
    preview_url: preview_text_path,              |
    ace_mode: 'markdown',                        |
    indent_width: %w(2 4 8),                     |
    tab_label: 'Edit post',                      |
    preview_label: 'Preview',                    |
    attribute: f.text_area(:raw) }               |

app/views/posts/_related_post.html.haml
.panel.panel-default
  .panel-heading
    Question list
  - if @posts.any?
    %table.table.table-hover.table-bordered
      - @posts.each do |p|
        %tr
          %td= link_to p.title, contest_post_path(p.contest.slug, p.contest.id, p.id)
  - else
    .panel-body
      You didn't submit a question.

app/views/posts/edit.html.haml
- content_for :title, "Editing #{@post.title}"

.row
  .col-md-10
    .panel.panel-default
      .panel-heading
        %h4= "Editing #{@post.title}"
      .panel-body
        = form_for @post.comments.first, url: post_path(@post), html: {role: 'form'} do |f|
          = render partial: 'form', locals: { f: f }
          = f.button 'Update', class: 'btn btn-warning'
          = link_to 'Cancel', problems_path

app/views/posts/index.html.haml
- content_for :title, 'Posts'

- if PostPolicy.new(current_user, :post).create?
  .row
    .col-md-12
      = button_to 'New Post', new_post_path, class: 'btn btn-primary pull-right', |
        html: { type: 'button' }, method: :get
.row
  .col-md-12
    .list-group.post-list
      - @posts.each do |p|
        .list-group-item.post-item
          - if p.first_comment.user
            .avatar= attachment_image_tag p.first_comment.user, :avatar, alt: p.first_comment.user.username, fallback: 'avatar.jpg'
          .content
            .list-group-item-heading= link_to p.title, post_path(p)
            .list-group-item-text
              .author= p.first_comment.user.username
      = paginate @posts, window: 3

app/views/posts/index_with_contest.html.haml
- content_for :title, 'Posts'

.pull-right
  = button_to 'New Post', new_post_path, class: 'btn btn-primary', |
    html: { type: 'button' }, method: :get
.row
  .col-md-12
    .list-group.post-list
      - @posts.each do |p|
        .list-group-item
          .list-group-item-heading= link_to p.title, post_path(p)
          .list-group-item-text
            .author= p.first_comment.user.username

app/views/posts/index_with_problem.html.haml
- content_for :title, 'Posts'

- url = new_post_path
- url = new_problem_post_path(@problem.slug, @problem.id) if @problem
.pull-right
  = button_to 'New Post', url, class: 'btn btn-primary', |
    html: { type: 'button' }, method: :get
.row
  .col-md-12
    .list-group.post-list
      - @posts.each do |p|
        .list-group-item
          .list-group-item-heading= link_to p.title, post_path(p)
          .list-group-item-text
            .author= p.first_comment.user.username

app/views/posts/new.html.haml
- content_for :title, 'New post'

.row
  .col-md-10
    .panel.panel-default
      .panel-heading
        %h4 Create a post
      .panel-body
        - url = posts_path
        - url = contest_posts_path(@contest.slug, @contest.id) if @contest
        - url = problem_posts_path(@problem.slug, @problem.id) if @problem
        = form_for :comment, url: url, html: {role: 'form'} do |f|
          = render partial: 'form', locals: { f: f }
          = f.button 'Create', class: 'btn btn-success'
          = link_to 'Cancel', @contest ? contest_path(@contest.slug, @contest.id) : posts_path
  - if @contest
    .col-md-2
      = render partial: 'posts/related_post'

app/views/posts/show.html.haml
- content_for :title, @post.title

- if staff?
  .admin-wrench.btn-group
    %button{type: 'button', class: 'btn btn-default dropdown-toggle',
        data: {toggle: 'dropdown'}, aria: {expanded: 'false'}}
      %i.fa.fa-wrench
    %ul.dropdown-menu.pull-right{ role: 'menu' }
      %li= link_to 'Delete post', post_path(@post), method: :delete, data: { confirm: 'Are you sure?' }
      %li= link_to 'Pinned/Unpined at home page', post_pinned_path(@post), method: :put, remote: true
      %li= link_to 'Toggle visble', post_visible_path(@post), method: :put, remote: true

- if params[:contest_id]
  - contest = Contest.find(params[:contest_id])
  .row
    .col-md-12
      %ol.breadcrumb
        %li= link_to 'Home', root_path
        %li= link_to 'Contests', contests_path
        %li= link_to contest.title, contest_path(contest.slug, contest.id)
        %li.active problem

- if params[:problem_id]
  - problem = Problem.find(params[:problem_id])
  .row
    .col-md-12
      %ol.breadcrumb
        %li= link_to 'Home', root_path
        %li= link_to 'Problem', problems_path
        %li= link_to problem.title, problem_path(problem.slug, problem.id)
        %li= link_to 'Posts', problem_posts_path(problem.slug, problem.id)
        %li.active problem

.row
  .col-md-12
    .post.post-box
      .meta.clearfix
        %h2.pull-left= @post.title
        = attachment_image_tag @post.first_comment.user, :avatar, :limit, 50, 50,
            alt: @post.first_comment.user.name, class: 'pull-right'
      .content
        - if current_user && current_user.admin?
          %span.pull-right= link_to 'Edit', edit_post_path(@post)
        = raw @post.first_comment.baked
    .comments.post-box
      - @post.comments[1..-1].each do |c|
        .comment
          .heading
            = attachment_image_tag c.user, :avatar, :limit, 50, 50, alt: c.user.name
            = link_to c.user.name, user_path(c.user)
            %span.text-muted= c.created_at.to_formatted_s(:long_add_second)
            %span.text-muted.pull-right= link_to 'Delete', post_comment_path(@post, c), method: :delete, data: { confirm: 'Are you sure?' }
          .content
            = raw c.baked

- if current_user
  .row
    .col-md-12
      = form_for [@post, @comment], html: { class: 'post-box' } do |f|
        .meta
          Add a new comment
        .content
          = f.text_area :raw
          %button.btn.btn-success Reply