config/routes.rb
Rails.application.routes.draw do
  resources :users, param: :username do
    resources :notes
  end
  get '/users/:username/admin', to: 'users#grant_admin', as: :user_grant_admin
  get '/users/:username/moderator', to: 'users#grant_moderator', as: :user_grant_moderator
  get '/users/:username/block', to: 'users#block', as: :user_block
  post '/users/is_local_username', to: 'users#is_local_username'
  get '/users/search/users', to: 'users#search_users'

  resources :groups, param: :group_name

  resources :delayable_contests, controller: 'contests', type: 'DelayableContest', except: :show

  get '/contests', to: 'contests#index', as: :contests
  post '/contests', to: 'contests#create'
  get '/contests/new', to: 'contests#new', as: :new_contest
  get '/c/:slug/:id', to: 'contests#show', constraints: {id: /\d+/}, as: :contest
  get '/c/:slug/:id/edit', to: 'contests#edit', constraints: {id: /\d+/}, as: :edit_contest
  match '/c/:slug/:id', to: 'contests#update', constraints: {id: /\d+/}, via: [:patch, :put]
  delete '/c/:slug/:id', to: 'contests#destroy', constraints: {id: /\d+/}
  get 'c/:slug/:id/notifications/new', to: 'contests#new_notification', constraints: {id: /\d+/}, as: :new_contest_notification
  post 'c/:slug/:id/notifications', to: 'contests#create_notification', constraints: {id: /\d+/}, as: :contest_notifications
  get '/c/:slug/:id/ranking', to: 'contests#ranking', constraints: {id: /\d+/}, as: :contest_ranking
  get '/c/:slug/:contest_id/solutions', to: 'contests#solutions', constraints: {contest_id: /\d+/}, as: :contest_solutions
  post '/c/:slug/:contest_id/solutions', to: 'contests#create_solution', constraints: {contest_id: /\d+/}
  get '/c/:slug/:contest_id/posts', to: 'posts#index_with_contest', constraints: {contest_id: /\d+/}, as: :contest_posts
  post '/c/:slug/:contest_id/posts', to: 'posts#create_with_contest', constraints: {contest_id: /\d+/}
  get '/c/:slug/:contest_id/posts/new', to: 'posts#new_with_contest', constraints: {contest_id: /\d+/}, as: :new_contest_post
  get '/c/:slug/:contest_id/:post_id', to: 'posts#show_with_contest', constraints: {contest_id: /\d+/, post_id: /\d+/}, as: :contest_post

  resources :posts do
    put '/pinned', to: 'posts#toggle_pinned', as: :pinned
    put '/visible', to: 'posts#toggle_visible', as: :visible
    resources :comments
  end
  resources :solutions do
    get '/report', to: 'solutions#report'
  end
  get '/problems', to: 'problems#index', as: :problems
  post '/problems', to: 'problems#create'
  get '/problems/new', to: 'problems#new', as: :new_problem
  get '/p/:slug/:id', to: 'problems#show', constraints: {id: /\d+/}, as: :problem
  get '/p/:slug/:id/edit', to: 'problems#edit', constraints: {id: /\d+/}, as: :edit_problem
  match '/p/:slug/:id', to: 'problems#update', constraints: {id: /\d+/}, via: [:patch, :put]
  delete '/p/:slug/:id', to: 'problems#destroy', constraints: {id: /\d+/}
  get '/p/:slug/:problem_id/posts', to: 'posts#index_with_problem', constraints: {id: /\d+/}, as: :problem_posts
  post '/p/:slug/:problem_id/posts', to: 'posts#create_with_problem', constraints: {id: /\d+/}
  get '/p/:slug/:problem_id/posts/new', to: 'posts#new_with_problem', constraints: {id: /\d+/}, as: :new_problem_post
  get '/p/:slug/:problem_id/posts/:post_id', to: 'posts#show_with_problem', constraints: {id: /\d+/}, as: :problem_post
  delete '/p/:slug/:id', to: 'problems#destroy', constraints: {id: /\d+/}
  post '/problems/import', to: 'problems#import', as: :problems_import
  get '/problems/:id/excerpt', to: 'problems#excerpt'
  get '/p/:slug/:problem_id/solutions', to: 'problems#solutions', constraints: { problem_id: /\d+/ }, as: :problem_solutions
  post '/p/:slug/:problem_id/solutions', to: 'problems#create_solution', constraints: { problem_id: /\d+/ }

  namespace :admin do
    get '/dashboard', to: 'admin#dashboard'
    scope :settings do
      get '/:category', to: 'admin#show_settings', as: :settings
      put '/:category', to: 'admin#update_settings'
    end
    get '/groups', to: 'admin#groups', as: :groups
    post '/groups', to: 'admin#create_group'
    get '/groups/:group_name', to: 'admin#group', as: :group
    put '/groups/:group_name', to: 'admin#update_group'
    get '/uploads', to: 'admin#uploads_index', as: :uploads

    root to: 'admin#dashboard'
  end

  resources :uploads

  post '/preview/text', to: 'preview#preview_text', as: :preview_text
  post '/preview/code', to: 'preview#preview_code', as: :preview_code

  get '/settings/profile', to: 'user_settings#profile', as: :settings_profile
  post '/settings/profile', to: 'user_settings#update_profile'
  get '/settings/account', to: 'user_settings#account', as: :settings_account
  post '/settings/account', to: 'user_settings#update_account'
  post '/settings/email', to: 'user_settings#update_email', as: :settings_email
  get '/settings/notifications', to: 'user_settings#notification', as: :settings_notification
  post '/settings/notifications', to: 'user_settings#update_notification'

  get '/signup', to: 'users#new', as: :registration
  get '/login', to: 'sessions#new', as: :login
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy', as: :logout
  get '/about', to: 'statics#about', as: :about
  get '/help', to: 'statics#help', as: :help

  get '/query', to: 'search#query'
  get '/notifications', to: 'notifications#recent'
  post '/notifications/read', to: 'notifications#read'

  get '/rabbitmq', to: 'proxies#rabbitmq'

  root to: 'statics#home'
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :group_users, dependent: :destroy
  has_many :users, through: :group_users
  has_many :contest_groups
  has_many :contest, through: :contest_groups

  accepts_nested_attributes_for :users

  scope :visible, -> { where(visible: true) }

  validates_presence_of :name
  before_save :downcase_groupname

  def downcase_groupname
    self.group_name = group_name.downcase
  end

  def usernames
    users.pluck(:username).join(',')
  end

  def add(user)
    self.users.push(user)
  end

  def remove(user)
    self.groups_users.where(user: user).each(&:destroy)
  end

  protected

  def name_format_validator
    UsernameValidator.perform_validation(self, 'group_name')
  end

end

# == Schema Information
#
# Table name: groups
#
#  id         :integer          not null, primary key
#  name       :string           not null
#  visible    :boolean          default(TRUE), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  group_name :string
#
# Indexes
#
#  index_groups_on_name  (name) UNIQUE
#

app/views/admin/admin/_navbar.html.haml
%nav#admin-navbar
  %ul.nav.nav-pills
    %li{ role: "presentation #{active_class_if_admin_action('dashboard')}"}
      = link_to 'Dashboard', admin_dashboard_path
    %li{ role: "presentation #{active_class_if_admin_action('show_settings')}"}
      = link_to 'Settings', admin_settings_path('required')
    %li{ role: "presentation #{active_class_if_admin_action('groups')}"}
      = link_to 'Groups', admin_groups_path
    %li{ role: "presentation #{active_class_if_admin_action('uploads')}"}
      = link_to 'Uploads', admin_uploads_path

app/views/admin/admin/dashboard.html.haml
- content_for :title, 'Dashboard'
= render partial: 'admin/admin/navbar'

app/views/admin/admin/group.html.haml
- content_for :title, @group.name
= render partial: 'admin/admin/navbar'

.row
  .col-md-3
    /%input.search-for-group.form-control{ placeholder: 'Filter the group name' }
    .list-group
      - Group.all.each do |g|
        = link_to g.name, admin_group_path(g.group_name), class: 'list-group-item'
    %button.add.btn.btn-default{ data: { toggle: 'modal', target: '#add-group' } } Add
  .col-md-9
    = form_for @group, { url: admin_group_path(@group.group_name), accept: { charset: 'UTF-8' }, method: :put } do |f|
      .form-group
        %label.control-label{ for: 'group_name' }
          Group name(only English characters)
        = f.text_field :group_name, class: 'form-control'
      .form-group
        %label.control-label{ for: 'group_name' }
          Name(Shown for public)
        = f.text_field :name, class: 'form-control'
      .form-group
        %label.control-label{ for: 'users' }
          Users
        = f.collection_select :user_ids, @group.users, :id, :username,
            { selected: @group.user_ids }, { id: 'group-users', multiple: true }
      .form-group
        %label.control-label{ for: 'visible' }
          Visible
          = f.check_box :visible
      %button{ type: 'submit', class: 'btn btn-warning' }
        Update

#add-group.modal.fade{ tabindex: '-1', role: 'dialog', aria: { labelledby: 'Add new group', hidden: 'true' } }
  .modal-dialog
    .modal-content
      = form_for :group, { url: admin_groups_path, accept: { charset: 'UTF-8' }, method: :post } do |f|
        .modal-header
          %button{type: 'button', class: 'close', data: {dismiss: 'modal', label: 'Close'}}
            %span{aria: {hidden: 'true'}}
              &times;
          %h4#import-problem-label.modal-title
            Add new group
        .modal-body
          .form-group
            = f.label :group_name, 'Group name(only English characters)', class: 'control-label'
            %label.control-label{ for: 'group_name' }
            = f.text_field :group_name, class: 'form-control'
          .form-group
            = f.label :name, 'Name(Shown for public)', class: 'control-label'
            = f.text_field :name, class: 'form-control'
          .form-group
            = f.label :visible, class: 'control-label'
            = f.check_box :visible, value: 'yes'
        .modal-footer
          %button{type: 'button', class: 'btn btn-default', data: {dismiss: 'modal'}}
            Close
          %button{type: 'submit', class: 'btn btn-success'}
            Create

app/views/admin/admin/groups.html.haml
- content_for :title, 'Groups'
= render partial: 'admin/admin/navbar'

.row
  .col-md-3
    /%input.search-for-group.form-control{ placeholder: 'Filter the group name' }
    .list-group
      - Group.all.each do |g|
        = link_to g.name, admin_group_path(g.group_name), class: 'list-group-item'
    %button.add.btn.btn-default{ data: { toggle: 'modal', target: '#add-group' } } Add
  .col-md-9

#add-group.modal.fade{ tabindex: '-1', role: 'dialog', aria: { labelledby: 'Add new group', hidden: 'true' } }
  .modal-dialog
    .modal-content
      = form_for :group, { url: admin_groups_path, accept: { charset: 'UTF-8' }, method: :post } do |f|
        .modal-header
          %button{type: 'button', class: 'close', data: {dismiss: 'modal', label: 'Close'}}
            %span{aria: {hidden: 'true'}}
              &times;
          %h4#import-problem-label.modal-title
            Add new group
        .modal-body
          .form
            .form-group
              %label.control-label{ for: 'group_name' }
                Group name(only English characters)
              = text_field_tag :group_name, nil, class: 'form-control'
            .form-group
              %label.control-label{ for: 'group_name' }
                Name(Shown for public)
              = text_field_tag :name, nil, class: 'form-control'
        .modal-footer
          %button{type: 'button', class: 'btn btn-default', data: {dismiss: 'modal'}}
            Close
          %button{type: 'submit', class: 'btn btn-primary'}
            Create

app/views/admin/admin/settings.html.haml
- content_for :title, 'Settings - Admin'
= render partial: 'admin/admin/navbar'

.row
  .col-md-3
    .list-group
      - SiteSetting.category_listings.each do |category|
        = link_to category, admin_settings_path(category),               |
          class: "list-group-item #{active_class_if_category(category)}" |
  .col-md-9
    = form_for :settings,                             |
      html: {role: 'form', class: 'form-horizontal'}, |
      method: :put do |f|                             |
      - @settings.each do |s|
        .form-group
          = label_tag s[:setting], s[:setting], class: 'col-md-3 control-label'
          .col-md-7
            = text_field_tag s[:setting],       |
              s[:value],                        |
              name: "settings[#{s[:setting]}]", |
              placeholder: s[:default],         |
              class: 'form-control'             |
            %p= s[:description]
          .col-md-2
            - if s[:value] != s[:default]
              %button.btn.btn-default{:type => "button"}
                Restore to default
      .form-group
        .col-md-offset-3.col-md-9
          = f.submit class: 'btn btn-warning'

app/views/admin/admin/uploads_index.html.haml
- content_for :title, 'Uploads - Admin'
= render partial: 'admin/admin/navbar'

.row
  .col-md-12
    = form_for @upload, url: uploads_path, html: { role: 'form' } do |f|
      = f.attachment_field :upload, direct: true
      = f.button 'Upload', class: 'btn btn-default'

.row
  .col-md-12
    %table.table.table-bordered.table-hover
      %thead
        %tr
          %th ID
          %th Name
          %th Url
      %tbody
        - @uploads.each do |u|
          %tr
            %td= u.id
            %td= u.upload_filename
            %td= '/new' + attachment_url(u, :upload)