config/routes.rb
Rails.application.routes.draw do
  resources :users, param: :username do
    resources :notes
  end
  get '/users/:username/admin', to: 'users#grant_admin', as: :user_grant_admin
  get '/users/:username/moderator', to: 'users#grant_moderator', as: :user_grant_moderator
  get '/users/:username/block', to: 'users#block', as: :user_block
  post '/users/is_local_username', to: 'users#is_local_username'
  get '/users/search/users', to: 'users#search_users'

  resources :groups, param: :group_name

  resources :delayable_contests, controller: 'contests', type: 'DelayableContest', except: :show

  get '/contests', to: 'contests#index', as: :contests
  post '/contests', to: 'contests#create'
  get '/contests/new', to: 'contests#new', as: :new_contest
  get '/c/:slug/:id', to: 'contests#show', constraints: {id: /\d+/}, as: :contest
  get '/c/:slug/:id/edit', to: 'contests#edit', constraints: {id: /\d+/}, as: :edit_contest
  match '/c/:slug/:id', to: 'contests#update', constraints: {id: /\d+/}, via: [:patch, :put]
  delete '/c/:slug/:id', to: 'contests#destroy', constraints: {id: /\d+/}
  get 'c/:slug/:id/notifications/new', to: 'contests#new_notification', constraints: {id: /\d+/}, as: :new_contest_notification
  post 'c/:slug/:id/notifications', to: 'contests#create_notification', constraints: {id: /\d+/}, as: :contest_notifications
  get '/c/:slug/:id/ranking', to: 'contests#ranking', constraints: {id: /\d+/}, as: :contest_ranking
  get '/c/:slug/:contest_id/solutions', to: 'contests#solutions', constraints: {contest_id: /\d+/}, as: :contest_solutions
  post '/c/:slug/:contest_id/solutions', to: 'contests#create_solution', constraints: {contest_id: /\d+/}
  get '/c/:slug/:contest_id/posts', to: 'posts#index_with_contest', constraints: {contest_id: /\d+/}, as: :contest_posts
  post '/c/:slug/:contest_id/posts', to: 'posts#create_with_contest', constraints: {contest_id: /\d+/}
  get '/c/:slug/:contest_id/posts/new', to: 'posts#new_with_contest', constraints: {contest_id: /\d+/}, as: :new_contest_post
  get '/c/:slug/:contest_id/:post_id', to: 'posts#show_with_contest', constraints: {contest_id: /\d+/, post_id: /\d+/}, as: :contest_post

  resources :posts do
    put '/pinned', to: 'posts#toggle_pinned', as: :pinned
    put '/visible', to: 'posts#toggle_visible', as: :visible
    resources :comments
  end
  resources :solutions do
    get '/report', to: 'solutions#report'
  end
  get '/problems', to: 'problems#index', as: :problems
  post '/problems', to: 'problems#create'
  get '/problems/new', to: 'problems#new', as: :new_problem
  get '/p/:slug/:id', to: 'problems#show', constraints: {id: /\d+/}, as: :problem
  get '/p/:slug/:id/edit', to: 'problems#edit', constraints: {id: /\d+/}, as: :edit_problem
  match '/p/:slug/:id', to: 'problems#update', constraints: {id: /\d+/}, via: [:patch, :put]
  delete '/p/:slug/:id', to: 'problems#destroy', constraints: {id: /\d+/}
  get '/p/:slug/:problem_id/posts', to: 'posts#index_with_problem', constraints: {id: /\d+/}, as: :problem_posts
  post '/p/:slug/:problem_id/posts', to: 'posts#create_with_problem', constraints: {id: /\d+/}
  get '/p/:slug/:problem_id/posts/new', to: 'posts#new_with_problem', constraints: {id: /\d+/}, as: :new_problem_post
  get '/p/:slug/:problem_id/posts/:post_id', to: 'posts#show_with_problem', constraints: {id: /\d+/}, as: :problem_post
  delete '/p/:slug/:id', to: 'problems#destroy', constraints: {id: /\d+/}
  post '/problems/import', to: 'problems#import', as: :problems_import
  get '/problems/:id/excerpt', to: 'problems#excerpt'
  get '/p/:slug/:problem_id/solutions', to: 'problems#solutions', constraints: { problem_id: /\d+/ }, as: :problem_solutions
  post '/p/:slug/:problem_id/solutions', to: 'problems#create_solution', constraints: { problem_id: /\d+/ }

  namespace :admin do
    get '/dashboard', to: 'admin#dashboard'
    scope :settings do
      get '/:category', to: 'admin#show_settings', as: :settings
      put '/:category', to: 'admin#update_settings'
    end
    get '/groups', to: 'admin#groups', as: :groups
    post '/groups', to: 'admin#create_group'
    get '/groups/:group_name', to: 'admin#group', as: :group
    put '/groups/:group_name', to: 'admin#update_group'
    get '/uploads', to: 'admin#uploads_index', as: :uploads

    root to: 'admin#dashboard'
  end

  resources :uploads

  post '/preview/text', to: 'preview#preview_text', as: :preview_text
  post '/preview/code', to: 'preview#preview_code', as: :preview_code

  get '/settings/profile', to: 'user_settings#profile', as: :settings_profile
  post '/settings/profile', to: 'user_settings#update_profile'
  get '/settings/account', to: 'user_settings#account', as: :settings_account
  post '/settings/account', to: 'user_settings#update_account'
  post '/settings/email', to: 'user_settings#update_email', as: :settings_email
  get '/settings/notifications', to: 'user_settings#notification', as: :settings_notification
  post '/settings/notifications', to: 'user_settings#update_notification'

  get '/signup', to: 'users#new', as: :registration
  get '/login', to: 'sessions#new', as: :login
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy', as: :logout
  get '/about', to: 'statics#about', as: :about
  get '/help', to: 'statics#help', as: :help

  get '/query', to: 'search#query'
  get '/notifications', to: 'notifications#recent'
  post '/notifications/read', to: 'notifications#read'

  get '/rabbitmq', to: 'proxies#rabbitmq'

  root to: 'statics#home'
end

app/views/layouts/_footer.html.haml
%footer#footer
  .container
    .cat-logo
      = image_tag ['pirate-cat.png', 'cat-acrobat.png', 'cat-birdhouse.png', 'cat-cart.png',
                   'cat-gift.png', 'cat-hungry.png', 'cat-laptop.png', 'cat-paper.png',
                   'cat-rascal.png', 'cat-sleep.png', 'cat-upsidedown.png'].sample
    .row
      .col-md-7
        © 2014 - 2015
        %a{ href: 'https://github.com/DHUers/rigidoj', title: "Rigidoj's Github" }
          Powered by RigidOJ.
      .col-md-5
        %ul.footer-nav.navbar
          %li= link_to 'Help', help_path
          %li= link_to 'About', about_path

app/views/layouts/_head.html.haml
%meta{:charset => "UTF-8"}/
%meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}/
%title= "#{yield(:title)} - #{SiteSetting.title}"
%meta{:content => SiteSetting.site_description, :name => "description"}/
%meta{:content => "width=device-width,initial-scale=1,user-scalable=no", :name => "viewport"}/
%link{:href => SiteSetting.favicon_url, :rel => "shortcut icon", :type => "image/x-icon"}/
%link{:href => SiteSetting.apple_touch_icon_url, :rel => "apple-touch-icon", :sizes => "256x256"}/
== <!--[if lt IE 9]>
= javascript_include_tag 'html5shiv'
== <![endif]-->
= javascript_include_tag 'application', 'data-turbolinks-track' => true

app/views/layouts/_header.html.haml
%nav.navbar.navbar-default.navbar-fixed-top{ role: 'navigation'}
  .container
    .navbar-header
      %button.navbar-toggle.collapsed{"data-target" => "#navbar-drawer", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %i.fa.fa-bars
      = link_to root_path, class: 'navbar-brand' do
        %img{:src => SiteSetting.logo_url, :width => "32"}/
    #navbar-drawer.collapse.navbar-collapse
      %form.navbar-form.navbar-left.hidden{:role => "search"}
        .form-group
          %input#search-box.form-control{:placeholder => "Search", :type => "text"}/
      %ul.nav.navbar-nav.navbar-links
        %li= link_to 'Problem', problems_path
        %li= link_to 'Contest', contests_path
        %li= link_to 'Solution', solutions_path
        - if current_user
          %li= link_to 'Post', posts_path
        %li= link_to 'Help', help_path
      %ul.nav.navbar-nav.navbar-right
        - unless current_user
          %li= link_to 'Sign Up', registration_path
          %li
            = link_to login_path, class: 'login-btn' do
              %button.btn.btn-default.navbar-btn{:type => "button"} Log In
        - else
          %li= render partial: 'components/notification_badge'
          %li
            %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-no-turbolink" => "", "data-target" => "#", "data-toggle" => "dropdown", :href => user_path(current_user), :role => "button"}
              = current_user.username
              %i.fa.fa-caret-down
            %ul.dropdown-menu{:role => "menu"}
              %li= link_to 'My profile', user_path(current_user)
              %li= link_to 'Settings', settings_profile_path
              /%li= link_to 'Bookmarks', "/users/#{current_user.username_lower}/bookmarks"
              /%li= link_to 'Notes', user_notes_path(current_user)
              - if staff?
                %li= link_to 'Admin', admin_dashboard_path
              %li.divider
              %li= link_to 'Log out', logout_path, method: :delete, data: { confirm: 'Are you sure?' }

app/views/layouts/_navless_header.html.haml
%nav.navbar.navbar-success.navbar-fixed-top{:role => "navigation"}
  .container
    .navbar-header
      %button.navbar-toggle.collapsed{"data-target" => "#navbar-drawer", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only 切换导航面板
        %i.fa.fa-bars
      = link_to 'Brand', root_path, class: 'navbar-brand'
    #navbar-drawer.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li= link_to 'Problem', problems_path
        %li= link_to 'Contest', contests_path
        %li= link_to 'Post', posts_path
        %li.dropdown
          %a.dropdown-toggle{"aria-expanded" => "false", "data-toggle" => "dropdown", :href => "#", :role => "button"}
            More
            %i.fa.fa-caret-down
          %ul.dropdown-menu{:role => "menu"}
            %li= link_to 'Help', help_path
            %li.divider
            %li= link_to 'About', about_path
      %ul.nav.navbar-nav.navbar-right
        %li= link_to 'Log in', login_path
        %li= link_to 'Sign up', registration_path

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    = render partial: 'layouts/head'
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    /[if lt IE 8]
      <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    = render partial: 'layouts/header'
    %section#main
      .container
        - flash.each do |type, msg|
          %div{ class: "alert alert-#{type} fade in", role: 'alert' }
            %button.close{ data: { dismiss: 'alert' } } ×
            = msg
        = yield
    = render partial: 'layouts/footer'

app/views/layouts/landing.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "UTF-8"}/
    %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}/
    %title= SiteSetting.title
    %meta{:content => SiteSetting.site_description, :name => "description"}/
    %meta{:content => "width=device-width,initial-scale=1,user-scalable=no", :name => "viewport"}/
    %link{ href: SiteSetting.favicon_url, :rel => "shortcut icon", :type => "image/x-icon"}/
    %link{ href: SiteSetting.apple_touch_icon_url, :rel => "apple-touch-icon", :sizes => "256x256"}/
    /[if lt IE 9]
      <haml:loud> javascript_include_tag &amp;#39;html5shiv&amp;#39; </haml:loud>
    = javascript_include_tag 'landing', 'data-turbolinks-track' => false
    = stylesheet_link_tag    'landing', media: 'all', 'data-turbolinks-track' => false
  %body
    /[if lt IE 8]
      <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    = yield